repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix, --unsafe-fixes]
        exclude: |
          (?x)^(
            attic/|
            _apps/|
            services/_deprecated_.* 
          )
      - id: ruff-format
        name: ruff (format)
        # bez --force-exclude (hook już to dodaje)
        exclude: |
          (?x)^(
            attic/|
            _apps/|
            services/_deprecated_.* 
          )
