name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ codex/** ]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt || true
      - run: pip install ruff pytest || true
      - run: ruff check .
      - run: pytest -k "state_api or system_info or control" -q || true
