name: Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Ruff
        run: pip install "ruff==0.13.1"

      - name: Ruff version
        run: ruff --version

      - name: Check formatting (ruff format --check)
        run: ruff format --check --diff .

      - name: Lint (PR annotations)
        run: ruff check . --output-format=github

      # (opcjonalnie) dodatkowe statystyki w zwykłym formacie do logów
      # - name: Lint stats
      #   run: ruff check . --statistics